import {
    deletePhoto,
    generateUploadUrl,
    getContactSettings,
    getPhotoList,
    getReels,
    getYouTubeUrl,
    saveContactSettings,
    savePhotoList,
    saveReels,
    saveYouTubeUrl,
    generatePdfUploadUrl,
    saveProductCatalogue,
    getProductCatalogue,
    deleteProductCatalogue,
} from "./functions";

export const router = {
    generateUploadUrl,
    savePhotoList,
    getPhotoList,
    saveYouTubeUrl,
    getYouTubeUrl,
    saveReels,
    getReels,
    deletePhoto,
    saveContactSettings,
    getContactSettings,
    generatePdfUploadUrl,
    saveProductCatalogue,
    getProductCatalogue,
    deleteProductCatalogue,
};
