/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/products-names": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProductNames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProductNames: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            names: {
                                id: number;
                                name: string;
                            }[];
                            meta: {
                                total: number;
                            };
                        };
                    };
                };
            };
            /** @description 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json":
                        | {
                              /** @constant */
                              defined: true;
                              /** @constant */
                              code: "BAD_REQUEST";
                              /** @constant */
                              status: 400;
                              /** @default The request was invalid or cannot be served. */
                              message: string;
                              data?: Record<string, never> | null;
                          }
                        | {
                              /** @constant */
                              defined: false;
                              code: string;
                              status: number;
                              message: string;
                              data?: unknown;
                          };
                };
            };
            /** @description 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json":
                        | {
                              /** @constant */
                              defined: true;
                              /** @constant */
                              code: "UNAUTHORIZED";
                              /** @constant */
                              status: 401;
                              /** @default You are not authorized to perform this action. */
                              message: string;
                              data?: Record<string, never> | null;
                          }
                        | {
                              /** @constant */
                              defined: false;
                              code: string;
                              status: number;
                              message: string;
                              data?: unknown;
                          };
                };
            };
            /** @description 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json":
                        | {
                              /** @constant */
                              defined: true;
                              /** @constant */
                              code: "NOT_FOUND";
                              /** @constant */
                              status: 404;
                              /** @default The requested resource was not found. */
                              message: string;
                              data?: Record<string, never> | null;
                          }
                        | {
                              /** @constant */
                              defined: false;
                              code: string;
                              status: number;
                              message: string;
                              data?: unknown;
                          };
                };
            };
            /** @description 500 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json":
                        | {
                              /** @constant */
                              defined: true;
                              /** @constant */
                              code: "INTERNAL_SERVER_ERROR";
                              /** @constant */
                              status: 500;
                              /** @default An internal server error occurred. */
                              message: string;
                              data?: Record<string, never> | null;
                          }
                        | {
                              /** @constant */
                              defined: false;
                              code: string;
                              status: number;
                              message: string;
                              data?: unknown;
                          };
                };
            };
        };
    };
}
